### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by AvocadoHole** [nipkownix/re4_tweaks#289]
- [X] Game has been updated to the latest RE4HD release (v1.0.1: https://www.re4hd.com/?p=9471)
- [X] Data has been [validated with SFV](https://www.re4hd.com/?p=9454) (a guide to using QuickSFV is available at that link, use that with this 1.0.1 SFV: [BIO4-HDProject1.0.1-SFV.zip](https://github.com/nipkownix/re4_tweaks/files/8057899/BIO4-HDProject1.0.1-SFV.zip))

The game crashes on startup as long as dinput8.dll is present in the Bin32 folder, but starts up normally if removed.

Game version: 1.0.6, Clean Steam install and integrity verified files with RE4HD 1.1 release applied

CrashDumps folder produces no files upon startup attempt.

Specs:
Intel i7-8750H
Nvidia GTX 1060 Max-Q
16 GB RAM

**Comment by nipkownix** [comment]
Please create a folder called "CrashDumps" inside the bin32 folder, and try running the game again.
When it crashes, a zip will be created in that folder. Upload the folder here so we can take a look.
Also, please attach dinput8.log if you can.

**Comment by AvocadoHole** [comment]
Dinput8.log is attached, but there's still nothing in the CrashDumps folder.

[DINPUT8.log](https://github.com/nipkownix/re4_tweaks/files/9193936/DINPUT8.log)

**Comment by linkthehylian** [comment]
You specified that you did a clean install of RE4, right? I'm curious as to why your game version is `1.0.6` when it should be `1.1.0`. The only versions that are still on 1.0.6 are JP/GER. (might only apply for JP now since GER was recently uncensored)

Not that it should matter, but a fresh reinstall of the game should provide 1.1.0.

If it somehow doesn't, I've attached mine just in case.
[bio4.zip](https://github.com/nipkownix/re4_tweaks/files/9194426/bio4.zip)

**Comment by nipkownix** [comment]
> your game version is 1.0.6 when it should be 1.1.0

Not really. Some people who bought the game before update 1.1.0 was released still have 1.0.6. Capcom messed something up back then. "New" owners are guaranteed to receive 1.1.0, while other are stuck on 1.0.6, just like me.

There's nothing wrong with v1.0.6, though. No new features were added in v1.1.0, only minor changes and new languages.

@AvocadoHole
>but there's still nothing in the CrashDumps folder.

Strange. Can you check is this build creates something inside CrashDumps?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9194683/dinput8.zip)

**Comment by blank-teer** [comment]
I can confirm the subject issue. 
But I have a little different preconditions: 
- game ver is 1.1.0 (steam, purchased on this summer sale) 
- hdproject ver 1.1 

Removing dinput.dll lets the game start but the interface is messed up then.
Having dinput.dll produces crashes (silent ones: neither popups nor black screen) with no files created in the Bin32/CrashDumps folder. 

[DINPUT8.log](https://github.com/nipkownix/re4_tweaks/files/9194745/DINPUT8.log)

**Comment by blank-teer** [comment]
@nipkownix with this build all the same

**Comment by nipkownix** [comment]
Hmm, I see.
Would appreciate some more info about your system, such as:

Windows version;
Language;
Keyboard layout;

I'm assuming it is crashing when the keymap is being generated, not sure why though.

**Comment by linkthehylian** [comment]
> Not really. Some people who bought the game before update 1.1.0 was released still have 1.0.6. Capcom messed something up back then. "New" owners are guaranteed to receive 1.1.0, while others are stuck on 1.0.6, just like me.

There's nothing wrong with v1.0.6, though. No new features were added in v1.1.0, only minor changes and new languages.

Ahh, I was under the impression that only region exclusive versions were stuck on 1.0.6. I appreciate the info!

**Comment by blank-teer** [comment]
@nipkownix I fixed it! 
You're right, the root cause is language. I have two ones on my system: English and Russian. Seems like the issue might be with any language if it isn't supported by the game natively. 

So to fix you need to change the default keyboard input. In Win11 the toggle locates by: 
Settings -> Time and language -> Input -> Additional keyboard parameters -> Redefinition input method by default. 

I set it to English and the game started ideally!

**Comment by blank-teer** [comment]
Oops, here we go again... All was fine until I tried to look at the crashed car after killing the first hostile locals. The game crashes when I press E. Attaching dumps
[bio4.exe.20220727072743.zip](https://github.com/nipkownix/re4_tweaks/files/9195039/bio4.exe.20220727072743.zip)

**Comment by AvocadoHole** [comment]
> Strange. Can you check if this build creates something inside CrashDumps? [dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9194683/dinput8.zip)

Just attempted to relaunch and I'm still getting nothing. I'll see if it's language related as another user pointed out when I can.

**Comment by albertre4HD** [comment]
Hello! It seems Japanese keyboard is also suffering from the same problem.
You can read the comments from the user named Folico here:
https://www.re4hd.com/?page_id=9319

**Comment by AvocadoHole** [comment]
Changing the keyboard layout from serbian latin to US english allows the game to launch, and even to switch back when it has.

**Comment by Shevae9** [comment]
> Changing the keyboard layout from serbian latin to US english allows the game to launch, and even to switch back when it has.

I was just trying this right now and it worked. It worked the same way when I changed it from Turkish keyboard to English keyboard.

**Comment by emoose** [comment]
Hmm, my guess is the `ToUnicode` call inside `get_str_from_VK` is maybe not returning proper result for certain locales? Could be similar to the issue game itself had with key icons for certain locales, that involved `ToUnicode` too I think.

Maybe that's not returning a good result, leaving `wchar_t chars[5]` uninitialized, and then that gets passed to `WstrToStr`, which runs `std::wctomb`, and maybe causes an exception? Can't find much about that using exceptions though...

Maybe moving `Init_ExceptionHandler` somewhere earlier & testing with debug build might point us to where it's crashing.

**Comment by emoose** [comment]
> Oops, here we go again... All was fine until I tried to look at the crashed car after killing the first hostile locals. The game crashes when I press E.
> 
> Attaching dumps [bio4.exe.20220727072743.zip](https://github.com/nipkownix/re4_tweaks/files/9195039/bio4.exe.20220727072743.zip)

@blank-teer looks like that crash is happening with something animation related... maybe try verifying/redownloading if you can.

**Comment by nipkownix** [comment]
@blank-teer @AvocadoHole could you guys check if this build fixes the startup issues?
[dinput8.zip](https://github.com/nipkownix/re4_tweaks/files/9200043/dinput8.zip)

@albertre4HD I've been testing this one using JP language, so it should work fine there.

@emoose ``WstrToStr`` was crashing here: https://github.com/nipkownix/re4_tweaks/blob/83d9cf5dafc974faf5c8ff6924b7996e2817513c/dllmain/Utils.cpp#L30

Welp, that's what I get for using some random code from the internet.

>Maybe moving Init_ExceptionHandler somewhere earlier

Oh, I swear I thought ``Init_ExceptionHandler`` was in ``DllMain``. Meh.

**Comment by AvocadoHole** [comment]
@nipkownix 
This one works for starting it up on my end.

**Comment by blank-teer** [comment]
@nipkownix 
Works now, have tested it with default input settings with which got crashes previously.

**Comment by nipkownix** [comment]
Should be fixes as of the latest release.
Please let me know if anything weird pops up.
