### ISSUE TITLE
Can't move the mouse horizontal

### ISSUE THREAD

**Issue by PsxMicha** [nipkownix/re4_tweaks#489]
Hey! 

I am on a fresh install of RE4 and installed the HD project with the latest RE tweaks. 

When the game starts I can aim in any direction with the mouse. but as soon as I encounter the first enemy, I can only aim up and down. It feels like there's some sort of aim assist on. 

after that I can aim freely again, but as soon as I encounter a new enemy it's only vertical again.

I am using raw mouse input and I tried both mouse turning modes. 

any ideas?

**Comment by nipkownix** [comment]
This was a bug in a previous release. It should be fixed in version 1.8. Is that the one you're using?

**Comment by PsxMicha** [comment]
yes. I just downloaded the 1.8 release from here and copied it to my game folder. Problem still exist!

**Comment by nipkownix** [comment]
Hmm, just noticed it only happens when you encounter an enemy. It is a different problem, then.

I think the game does have some flags related to aim assist. Have you changed any of these flags using the F1 menu?

**Comment by PsxMicha** [comment]
I don't see any aim assist features in the F1 menu

**Comment by nipkownix** [comment]
![image](https://user-images.githubusercontent.com/33870163/226196558-de601f13-b1e3-4698-affb-a14567ec3e45.png)

Trainer > Flag Editor > "CONFIG" category > CFG_LOCK_ON

**Comment by PsxMicha** [comment]
that option wasn't ticked.. I tried it ticked and unticked.. no change. 

I reinstalled the game and tried without re_tweaks.. same problem :-\ So it's not even related to re4_tweaks. 

maybe you still have an idea?

**Comment by AztecGGWP** [comment]
Sup PsxMicha!
Im stuck on the same problem almost a year and i didnt find a way to solve it. You are the first how I saw with the same issue. 
I posted at steam community, reddit and tried to ask some re4 streamers, no one has a way to help. U find anything new?

**Comment by PsxMicha** [comment]
No sorry. I never played the game ever since and I don't remember if I fixed it
